// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRq91F-HEE6heUnIhKgwC2QluzVT4TBo',
    appId: '1:510668427219:web:974982cd35939e68b6e926',
    messagingSenderId: '510668427219',
    projectId: 'whatsapp-aysa',
    authDomain: 'whatsapp-aysa.firebaseapp.com',
    storageBucket: 'whatsapp-aysa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTKDN76TBuboPwxKPzOLDvNSTtNbucqeM',
    appId: '1:510668427219:android:24ad79ccd3c603eeb6e926',
    messagingSenderId: '510668427219',
    projectId: 'whatsapp-aysa',
    storageBucket: 'whatsapp-aysa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePGxCAfIiKR2h978L4gWr--sUcr7qK7k',
    appId: '1:510668427219:ios:c135f88cfd302798b6e926',
    messagingSenderId: '510668427219',
    projectId: 'whatsapp-aysa',
    storageBucket: 'whatsapp-aysa.appspot.com',
    iosBundleId: 'com.aysa.whatsapp.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePGxCAfIiKR2h978L4gWr--sUcr7qK7k',
    appId: '1:510668427219:ios:c135f88cfd302798b6e926',
    messagingSenderId: '510668427219',
    projectId: 'whatsapp-aysa',
    storageBucket: 'whatsapp-aysa.appspot.com',
    iosBundleId: 'com.aysa.whatsapp.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSRq91F-HEE6heUnIhKgwC2QluzVT4TBo',
    appId: '1:510668427219:web:ad87b0ca766f85d9b6e926',
    messagingSenderId: '510668427219',
    projectId: 'whatsapp-aysa',
    authDomain: 'whatsapp-aysa.firebaseapp.com',
    storageBucket: 'whatsapp-aysa.appspot.com',
  );
}
